# Generated by Django 5.2.7 on 2025-11-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_usertoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="authuser",
            name="last_password_reset",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Members"),
                    ("provider", "Providers"),
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                ],
                default="member",
            ),
        ),
    ]
