# Generated by Django 5.2.7 on 2025-12-08 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_authuser_last_password_reset_userprofile_role",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="label",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("work", "Work"),
                    ("billing", "billing"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter"),
                            ("linkedin", "LinkedIn"),
                        ],
                        max_length=30,
                    ),
                ),
                ("url", models.URLField(max_length=250)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to=settings.AUTH_USER_MODEL,
                        to_field="email",
                    ),
                ),
            ],
            options={
                "db_table": "social_links",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "platform"),
                        name="unique_user_social_platform",
                    )
                ],
            },
        ),
    ]
