# Generated by Django 5.2.7 on 2025-12-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_sociallink_business_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="street_line_2",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
