# Generated by Django 5.2.7 on 2026-01-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_sociallink_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="authuser",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
    ]
