# Generated by Django 5.2.7 on 2026-01-17 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_authuser_onboarding_step"),
        (
            "collaboration",
            "0007_rename_collaborati_status_99f444_idx_gigs_and_pr_status_bd51a1_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Professional bio shown on public profile",
                max_length=600,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary industry (top-level category)",
                limit_choices_to={"parent__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="collaboration.gigcategory",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="niches",
            field=models.ManyToManyField(
                blank=True,
                help_text="Selected niches (subcategories under industry)",
                limit_choices_to={"parent__isnull": False},
                related_name="profiles_niches",
                to="collaboration.gigcategory",
            ),
        ),
    ]
