# Generated by Django 5.2.7 on 2026-01-18 22:16

import accounts.models.onboarding
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_userprofile_bio_userprofile_industry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOnboardingIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intent",
                    models.JSONField(
                        help_text="Validated onboarding intent payload",
                        validators=[
                            accounts.models.onboarding.validate_onboarding_intents
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_intents",
                        to=settings.AUTH_USER_MODEL,
                        to_field="email",
                    ),
                ),
            ],
            options={
                "db_table": "user_onboarding_intents",
            },
        ),
    ]
