# Generated by Django 5.2.7 on 2026-01-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_rename_intent_useronboardingintent_intents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Members"),
                    ("provider", "Providers"),
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                ],
                default="member",
                max_length=30,
            ),
        ),
    ]
