# Generated by Django 5.2.7 on 2026-01-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0002_gigrole_description_alter_gigrole_role_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gigrole",
            old_name="role_title",
            new_name="niche_name",
        ),
        migrations.AddField(
            model_name="gigrole",
            name="role_id",
            field=models.PositiveIntegerField(
                help_text="Identifier for the subcategory under the main category",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gigrole",
            name="role_name",
            field=models.CharField(
                blank=True,
                help_text="Optional specific role title (e.g. Senior Frontend Engineer)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="gig",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("published", "Published"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
