# Generated by Django 5.2.7 on 2026-01-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collaboration",
            "0003_rename_role_title_gigrole_niche_name_gigrole_role_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="slug",
            field=models.SlugField(
                default="NuLL", editable=False, max_length=580, unique=True
            ),
            preserve_default=False,
        ),
    ]
