# Generated by Django 5.2.7 on 2026-01-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0004_gig_slug"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="gigrole",
            constraint=models.UniqueConstraint(
                fields=("gig", "niche", "role_id"),
                name="unique_gig_role_per_niche_professional",
            ),
        ),
    ]
