# Generated by Django 5.2.7 on 2026-01-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0006_alter_gig_status"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="gig",
            new_name="gigs_and_pr_status_bd51a1_idx",
            old_name="collaborati_status_99f444_idx",
        ),
        migrations.RenameIndex(
            model_name="gig",
            new_name="gigs_and_pr_creator_d28a30_idx",
            old_name="collaborati_creator_acc6c3_idx",
        ),
        migrations.RenameIndex(
            model_name="gigrole",
            new_name="gig_roles_gig_id_8de011_idx",
            old_name="collaborati_gig_id_db465c_idx",
        ),
        migrations.RenameIndex(
            model_name="gigrole",
            new_name="gig_roles_status_c41cb3_idx",
            old_name="collaborati_status_5c0371_idx",
        ),
        migrations.RenameIndex(
            model_name="gigrole",
            new_name="gig_roles_niche_i_b74a19_idx",
            old_name="collaborati_niche_i_52ca75_idx",
        ),
        migrations.AddIndex(
            model_name="gigcategory",
            index=models.Index(
                fields=["parent"], name="collaborati_parent__df3d84_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="gig",
            table="gigs_and_projects",
        ),
        migrations.AlterModelTable(
            name="gigapplication",
            table="gig_applications",
        ),
        migrations.AlterModelTable(
            name="gigassignment",
            table="gig_assignments",
        ),
        migrations.AlterModelTable(
            name="gigrole",
            table="gig_roles",
        ),
    ]
