# Generated by Django 5.2.7 on 2026-01-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0008_add_is_active_to_gig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gig",
            name="is_active",
        ),
    ]
