# Generated by Django 5.2.7 on 2026-01-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0010_gig_is_gig_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gigrole",
            name="workload",
        ),
        migrations.AddField(
            model_name="gigrole",
            name="payment_option",
            field=models.CharField(
                choices=[
                    ("full_upfront", "Full Upfront"),
                    ("split_50_50", "Split 50% / 50%"),
                    ("split_60_40", "Split 60% / 40%"),
                    ("split_70_30", "Split 70% / 30%"),
                    ("split_30_40_30", "Split 30% / 40% / 30%"),
                    ("split_40_30_30", "Split 40% / 30% / 30%"),
                    ("split_50_30_20", "Split 50% / 30% / 20%"),
                ],
                default="split_50_50",
                max_length=40,
            ),
        ),
    ]
