# payments/schemas/payment.py

from pydantic import BaseModel, ConfigDict, EmailStr, Field
from typing import Any, Dict, Literal


class PaymentGatewayRequest(BaseModel):
    """
    Standardized schema for payment initialization across all gateways.

    This model enforces data integrity for financial transactions, ensuring 
    that mandatory fields like idempotency keys and unique references are 
    validated before reaching the payment provider gateway class (Stripe, Paystack, etc.).

    Attributes:
        email (EmailStr): The customer's verified email address for receipts and tracking.
        amount (int): The transaction value in the smallest currency unit 
            (e.g., kobo for NGN, cents for USD). Must be greater than 0.
        reference (str): A unique, 12-character string used to identify and 
            reconcile the transaction in internal systems.
        idm_key (str): A unique idempotency key. Used to ensure that 
            retried requests do not result in duplicate charges.
        currency (str): The ISO 4217 three-letter currency code. Defaults to "USD".
    """
    email: EmailStr = Field(..., description="Customer's email address")
    amount: int = Field(..., gt=0, description="Amount in smallest unit (e.g kobo, cents)")
    reference: str = Field(..., min_length=19, max_length=19, description="Unique reference for the transaction")
    currency: str = Field(default="USD", min_length=3, max_length=3)
    

class ActivePaymentSession(BaseModel):
    """
    Represents the required identifiers for a payment in progress.
    
    This payload is used to bridge the gap between payment initiation and 
    final processing or verification. It ensures that the system can 
    uniquely identify the transaction and route it to the correct 
    third-party gateway.

    Attributes:
        reference (str): The unique transaction identifier generated by 
            our system during the initialization step. Used to look up 
            the pending record in the database.
        provider (str): The slug or name of the payment gateway (e.g., 'stripe', 
            'paystack') assigned to handle this transaction.
    """
    reference: str
    provider: str
    
class PaymentRedirectManifest(BaseModel):
    """
    The final response returned to the view when a payment is successfully initialized 
    with a provider and the user is ready to be redirected to the checkout.

    This object encapsulates the gateway's response (like the checkout URL) 
    and provides UI hints for the frontend notification system.
    """
    status: str
    title: str
    message: str
    data: Dict[str, Any] = Field(
        default_factory=dict, 
        description="Contains the gateway's response, including the checkout URL."
    )
    ui_intent: Literal["success", "warning", "error", "info"] = "success"


    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "summary": "Paystack Response",
                    "value": {
                        "status": "success",
                        "title": "Payment Initialized",
                        "message": "Redirecting to Paystack...",
                        "ui_intent": "success",
                        "data": {
                            "authorization_url": "https://checkout.paystack.com/0pk3904ntv",
                            "access_code": "0pk3904ntv",
                            "reference": "SRV-jSCgCj9KZ0NehGo"
                        }
                    }
                },
                {
                    "summary": "Stripe Response",
                    "value": {
                        "status": "success",
                        "title": "Checkout Ready",
                        "message": "Redirecting to Stripe secure server...",
                        "ui_intent": "success",
                        "data": {
                            "id": "cs_test_a1b2c3d4",
                            "url": "https://checkout.stripe.com/pay/cst_standard_session",
                            "payment_status": "unpaid"
                        }
                    }
                }
            ]
        }
    )
    