# Generated by Django 5.2.7 on 2025-12-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_accounts", "0002_alter_businessaccount_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessaccount",
            name="industry",
            field=models.CharField(max_length=70, null=True),
        ),
    ]
