# Generated by Django 5.2.7 on 2025-12-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_accounts", "0003_businessaccount_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessaccount",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
