# Generated by Django 5.2.7 on 2025-12-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_accounts", "0004_alter_businessaccount_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessaccount",
            name="tagline",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
