# Generated by Django 5.2.7 on 2026-01-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_accounts", "0006_businessaccount_logo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessaccount",
            name="niche",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
