# Generated by Django 5.2.7 on 2025-10-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="address",
            table="user_addresses",
        ),
        migrations.AlterModelTable(
            name="authuser",
            table="user_accounts",
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="user_profiles",
        ),
    ]
