# Generated by Django 5.2.7 on 2025-11-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_address_table_alter_authuser_table_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="alt_mobile_num",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="mobile_num",
            field=models.CharField(
                blank=True, max_length=18, null=True, unique=True
            ),
        ),
    ]
