# Generated by Django 5.2.7 on 2025-12-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_address_label_sociallink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="label",
            field=models.CharField(
                choices=[("home", "Home"), ("work", "Work"), ("billing", "billing")],
                default="home",
                max_length=20,
            ),
        ),
    ]
