# Generated by Django 5.2.7 on 2025-12-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_address_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="address",
            name="label",
            field=models.CharField(
                choices=[("home", "Home"), ("work", "Work"), ("billing", "Billing")],
                default="home",
                max_length=20,
            ),
        ),
    ]
