# Generated by Django 5.2.7 on 2025-12-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_address_country_alter_address_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
