# Generated by Django 5.2.7 on 2025-12-23 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_address_country"),
        ("business_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallink",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to="business_accounts.businessaccount",
            ),
        ),
        migrations.AddConstraint(
            model_name="sociallink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("business__isnull", False)),
                fields=("business", "platform"),
                name="unique_business_social_platform",
            ),
        ),
        migrations.AddConstraint(
            model_name="sociallink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("business__isnull", True), ("user__isnull", False)),
                    models.Q(("business__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="social_link_scope_check",
            ),
        ),
    ]
