# Generated by Django 5.2.7 on 2025-12-26 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_address_street_line_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
        ),
    ]
