# Generated by Django 5.2.7 on 2026-01-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_authuser_onboarding_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="authuser",
            name="onboarding_step",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
