# Generated by Django 5.2.7 on 2026-01-19 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_useronboardingintent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useronboardingintent",
            old_name="intent",
            new_name="intents",
        ),
        migrations.AlterField(
            model_name="useronboardingintent",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboarding_intents",
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
        ),
    ]
