from decimal import Decimal, ROUND_HALF_UP

APP_NAME = "servio"
APP_VERSION = "v1.2"

APP_SUBSCRIPTION_FEE = 40
USD_TO_NGN_RATE = Decimal("1400")

DECIMAL_PLACE = 0.01
SERVICE_FEE = 0.05
GST_TAX_FEE = 0.07
