[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = tests.py test_*.py *_tests.py
addopts =
    -v
    --strict-markers
    --tb=short
    --disable-warnings

markers =
    unit: fast, isolated tests
    integration: tests involving DB or multiple layers
    e2e: full system tests
    slow: long running tests

log_cli = true
log_cli_level = INFO
