# Generated by Django 5.2.7 on 2025-12-23 01:17

import business_accounts.models.business
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0009_alter_address_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "business_id",
                    models.CharField(
                        db_index=True,
                        default=business_accounts.models.business.generate_business_id,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("business_name", models.CharField(max_length=255)),
                ("tagline", models.CharField(blank=True, max_length=255)),
                ("business_email", models.EmailField(max_length=254)),
                ("business_phone", models.CharField(max_length=30)),
                ("niche", models.CharField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_restricted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="businesses",
                        to="accounts.address",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_businesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "business_account",
                "indexes": [
                    models.Index(fields=["slug"], name="business_ac_slug_a7994e_idx"),
                    models.Index(
                        fields=["business_id"], name="business_ac_busines_b229f9_idx"
                    ),
                ],
            },
        ),
    ]
