# Generated by Django 5.2.7 on 2025-12-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_accounts", "0005_alter_businessaccount_tagline"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessaccount",
            name="logo_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="businesses/logos"
            ),
        ),
    ]
