# Generated by Django 5.2.7 on 2025-12-31 01:10

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=350)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "total_budget",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overall estimated budget",
                        max_digits=12,
                    ),
                ),
                (
                    "is_negotiable",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the total budget is negotiable",
                    ),
                ),
                ("has_gig_roles", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gigs",
                        to=settings.AUTH_USER_MODEL,
                        to_field="email",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collaboration/Gigs",
                "db_table": "collaboration_gigs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GigCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable category name (e.g. Software Development)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly unique identifier for the category",
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Controls whether the category can be used for new gigs",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional parent category for hierarchical categorization",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategories",
                        to="collaboration.gigcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collaboration/Gig Category",
                "verbose_name_plural": "Collaboration/Gig Categories",
                "db_table": "collaboration_gig_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GigRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional specific role title (e.g. Senior Frontend Engineer)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "workload",
                    models.CharField(
                        choices=[
                            ("fixed_hours", "Fixed hours"),
                            ("flexible", "Flexible (result-based)"),
                        ],
                        default="fixed_hours",
                        max_length=40,
                    ),
                ),
                ("slots", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("open", "Open"),
                            ("completed", "Completed"),
                        ],
                        default="open",
                        max_length=40,
                    ),
                ),
                (
                    "is_negotiable",
                    models.BooleanField(
                        default=False, help_text="Indicates if the budget is negotiable"
                    ),
                ),
                ("show_role_budget", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="required_roles",
                        to="collaboration.gig",
                    ),
                ),
                (
                    "niche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roles",
                        to="collaboration.gigcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gig Role",
                "verbose_name_plural": "Gig Roles",
                "db_table": "collaboration_gig_roles",
            },
        ),
        migrations.CreateModel(
            name="GigAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agreed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The final agreed amount for this assignment",
                        max_digits=10,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_withdrawn", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="ongoing",
                        help_text="Current status of the assignment",
                        max_length=20,
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        help_text="The user assigned to this role",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gig_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gig_role",
                    models.ForeignKey(
                        help_text="The role this assignment belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="collaboration.gigrole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gig Assignment",
                "verbose_name_plural": "Gig Assignments",
                "db_table": "collaboration_gig_assignments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GigApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "proposed_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The amount proposed by the applicant for this role",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The agreed amount if the application is accepted",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from the applicant",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("negotiating", "Negotiating"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        help_text="The current status of the application",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user applying for the role",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gig_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gig_role",
                    models.ForeignKey(
                        help_text="The specific role this application is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="collaboration.gigrole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gig Application",
                "verbose_name_plural": "Gig Applications",
                "db_table": "collaboration_gig_applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="gig",
            index=models.Index(
                fields=["status", "visibility"], name="collaborati_status_99f444_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gig",
            index=models.Index(
                fields=["creator"], name="collaborati_creator_acc6c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gigcategory",
            index=models.Index(fields=["slug"], name="collaborati_slug_aa53f2_idx"),
        ),
        migrations.AddIndex(
            model_name="gigcategory",
            index=models.Index(
                fields=["is_active"], name="collaborati_is_acti_38cd70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gigrole",
            index=models.Index(
                fields=["gig", "status"], name="collaborati_gig_id_db465c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gigrole",
            index=models.Index(fields=["status"], name="collaborati_status_5c0371_idx"),
        ),
        migrations.AddIndex(
            model_name="gigrole",
            index=models.Index(fields=["niche"], name="collaborati_niche_i_52ca75_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="gigassignment",
            unique_together={("gig_role", "professional")},
        ),
        migrations.AlterUniqueTogether(
            name="gigapplication",
            unique_together={("gig_role", "user")},
        ),
    ]
