# Generated by Django 5.2.7 on 2026-01-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gigrole",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="gigrole",
            name="role_title",
            field=models.CharField(
                blank=True,
                default="EMPTY",
                help_text="Optional specific role title (e.g. Senior Frontend Engineer)",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
