# Generated by Django 5.2.7 on 2026-01-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0005_gigrole_unique_gig_role_per_niche_professional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gig",
            name="status",
            field=models.CharField(
                choices=[
                    ("archived", "Archived"),
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("published", "Published"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
