# Generated by Django 5.2.7 on 2026-01-23 04:20

from django.db import migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collaboration",
            "0007_rename_collaborati_status_99f444_idx_gigs_and_pr_status_bd51a1_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
