# Generated by Django 5.2.7 on 2026-01-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0009_remove_gig_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="is_gig_active",
            field=models.BooleanField(default=True),
        ),
    ]
