# Generated by Django 5.2.7 on 2026-01-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0011_remove_gigrole_workload_gigrole_payment_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gig",
            name="slug",
            field=models.SlugField(editable=False, max_length=230, unique=True),
        ),
    ]
